name: Build Docker images

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/build.yml
      - Dockerfile
  workflow_dispatch:

jobs:
  build-docker:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # 1.0.3
      - name: Build and push - frxyt/microsocks:1.0.3
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            DEBIAN_VERSION=bookworm
            MICROSOCKS_VERSION=1.0.3
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            frxyt/microsocks:1.0.3
            frxyt/microsocks:1.0.3-bookworm
            frxyt/microsocks:stable
      # 1.0.4
      - name: Build and push - frxyt/microsocks:1.0.4
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            DEBIAN_VERSION=trixie
            MICROSOCKS_VERSION=1.0.4
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            frxyt/microsocks:1.0.4
            frxyt/microsocks:1.0.4-trixie
            frxyt/microsocks:latest
